### ISSUE TITLE
Fix Police Vehicle Speeds

### ISSUE THREAD

**Issue by CptTompkins** [ShortWlf/fx-od-pub#13]
The Vehicle marked Police6, the Nissan GT-R has a current top speed when upgraded all the way of 117 MPH. Based on The IRL version of the car, the top speed should be 215 MPH, I would like this to be changed, that way the police have a chance of catching up with suspects who have cars that easily go 150 + MPH.

**Comment by ShortWlf** [comment]
https://gtamods.com/wiki/Vehicles.meta
