### ISSUE TITLE
Shooting while Handcuff

### ISSUE THREAD

**Issue by BigOgaming** [ShortWlf/fx-od-pub#2]
When you are handcuff you are still able to pull out your gun and shoot.

**Comment by ShortWlf** [comment]
added a check for if punching, into a false bool, " DisablePlayerFiring(ped, true) "

**Comment by ShortWlf** [comment]
using https://docs.fivem.net/docs/game-references/controls/ 
to get key number for letter " R "

**Comment by ShortWlf** [comment]
This has been fixed, another issue will be submitted separately for " running while tazed, cannot be tazed while handcuffed "

**Comment by ShortWlf** [comment]
fixed this issue, moving the disable functions from multiple locations to one source.
