### ISSUE TITLE
Char Creator Clothes Variations

### ISSUE THREAD

**Issue by ShortWlf** [ShortWlf/fx-od-pub#27]
Char Creator Clothes Variations

**Comment by Gamemastertwig** [comment]
Added several new outfits
Fixed issue with props not saving or saving on other outfits

**Comment by Gamemastertwig** [comment]
ToDo: Fix issues with masks not loading or if they load faces do not load

**Comment by ShortWlf** [comment]
on dev server i had to reset the entire character creation script to default, character creation would not take, if typed /open would reset to default avatar with no changes.

**Comment by ShortWlf** [comment]
going to be pushed to dev server
